version: '3'

services:
  typescript:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/typescript
    tty: true
    ports:
      - 5555:80
    container_name: typescript